version: "3.5"
services:
  spring-boot:
    image: spring-boot
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ${APPLICATION_ROOT_FOLDER}:/usr/src/application
      - ${MAVEN_SETTINGS_FOLDER}:/root/.m2
  db:
    image: 'postgres:13.2-alpine'
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data-db:z
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}